<?php
/**
 * JPJRecordsApi
 * PHP version 5
 *
 * @category Class
 * @package  iimmpact
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * IIMMPACT API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2020-09-14T13:01:14Z
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.17
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace iimmpact\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use iimmpact\ApiException;
use iimmpact\Configuration;
use iimmpact\HeaderSelector;
use iimmpact\ObjectSerializer;

/**
 * JPJRecordsApi Class Doc Comment
 *
 * @category Class
 * @package  iimmpact
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class JPJRecordsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation v1JpjDrivingLicenseGet
     *
     * @param  string $id_no id_no (required)
     * @param  string $id_type id_type (required)
     * @param  string $captcha captcha (optional)
     *
     * @throws \iimmpact\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \iimmpact\Model\DrivingLicenseRespone
     */
    public function v1JpjDrivingLicenseGet($id_no, $id_type, $captcha = null)
    {
        list($response) = $this->v1JpjDrivingLicenseGetWithHttpInfo($id_no, $id_type, $captcha);
        return $response;
    }

    /**
     * Operation v1JpjDrivingLicenseGetWithHttpInfo
     *
     * @param  string $id_no (required)
     * @param  string $id_type (required)
     * @param  string $captcha (optional)
     *
     * @throws \iimmpact\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \iimmpact\Model\DrivingLicenseRespone, HTTP status code, HTTP response headers (array of strings)
     */
    public function v1JpjDrivingLicenseGetWithHttpInfo($id_no, $id_type, $captcha = null)
    {
        $returnType = '\iimmpact\Model\DrivingLicenseRespone';
        $request = $this->v1JpjDrivingLicenseGetRequest($id_no, $id_type, $captcha);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\iimmpact\Model\DrivingLicenseRespone',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation v1JpjDrivingLicenseGetAsync
     *
     * 
     *
     * @param  string $id_no (required)
     * @param  string $id_type (required)
     * @param  string $captcha (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1JpjDrivingLicenseGetAsync($id_no, $id_type, $captcha = null)
    {
        return $this->v1JpjDrivingLicenseGetAsyncWithHttpInfo($id_no, $id_type, $captcha)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v1JpjDrivingLicenseGetAsyncWithHttpInfo
     *
     * 
     *
     * @param  string $id_no (required)
     * @param  string $id_type (required)
     * @param  string $captcha (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1JpjDrivingLicenseGetAsyncWithHttpInfo($id_no, $id_type, $captcha = null)
    {
        $returnType = '\iimmpact\Model\DrivingLicenseRespone';
        $request = $this->v1JpjDrivingLicenseGetRequest($id_no, $id_type, $captcha);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v1JpjDrivingLicenseGet'
     *
     * @param  string $id_no (required)
     * @param  string $id_type (required)
     * @param  string $captcha (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function v1JpjDrivingLicenseGetRequest($id_no, $id_type, $captcha = null)
    {
        // verify the required parameter 'id_no' is set
        if ($id_no === null || (is_array($id_no) && count($id_no) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id_no when calling v1JpjDrivingLicenseGet'
            );
        }
        // verify the required parameter 'id_type' is set
        if ($id_type === null || (is_array($id_type) && count($id_type) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id_type when calling v1JpjDrivingLicenseGet'
            );
        }

        $resourcePath = '/v1/jpj/driving-license';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($id_no !== null) {
            $queryParams['id_no'] = ObjectSerializer::toQueryValue($id_no);
        }
        // query params
        if ($id_type !== null) {
            $queryParams['id_type'] = ObjectSerializer::toQueryValue($id_type);
        }
        // query params
        if ($captcha !== null) {
            $queryParams['captcha'] = ObjectSerializer::toQueryValue($captcha);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation v1JpjDrivingTestResultsGet
     *
     * @param  string $id_no id_no (required)
     * @param  string $id_type id_type (required)
     * @param  string $captcha captcha (optional)
     *
     * @throws \iimmpact\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \iimmpact\Model\DrivingTestRespone
     */
    public function v1JpjDrivingTestResultsGet($id_no, $id_type, $captcha = null)
    {
        list($response) = $this->v1JpjDrivingTestResultsGetWithHttpInfo($id_no, $id_type, $captcha);
        return $response;
    }

    /**
     * Operation v1JpjDrivingTestResultsGetWithHttpInfo
     *
     * @param  string $id_no (required)
     * @param  string $id_type (required)
     * @param  string $captcha (optional)
     *
     * @throws \iimmpact\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \iimmpact\Model\DrivingTestRespone, HTTP status code, HTTP response headers (array of strings)
     */
    public function v1JpjDrivingTestResultsGetWithHttpInfo($id_no, $id_type, $captcha = null)
    {
        $returnType = '\iimmpact\Model\DrivingTestRespone';
        $request = $this->v1JpjDrivingTestResultsGetRequest($id_no, $id_type, $captcha);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\iimmpact\Model\DrivingTestRespone',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation v1JpjDrivingTestResultsGetAsync
     *
     * 
     *
     * @param  string $id_no (required)
     * @param  string $id_type (required)
     * @param  string $captcha (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1JpjDrivingTestResultsGetAsync($id_no, $id_type, $captcha = null)
    {
        return $this->v1JpjDrivingTestResultsGetAsyncWithHttpInfo($id_no, $id_type, $captcha)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v1JpjDrivingTestResultsGetAsyncWithHttpInfo
     *
     * 
     *
     * @param  string $id_no (required)
     * @param  string $id_type (required)
     * @param  string $captcha (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1JpjDrivingTestResultsGetAsyncWithHttpInfo($id_no, $id_type, $captcha = null)
    {
        $returnType = '\iimmpact\Model\DrivingTestRespone';
        $request = $this->v1JpjDrivingTestResultsGetRequest($id_no, $id_type, $captcha);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v1JpjDrivingTestResultsGet'
     *
     * @param  string $id_no (required)
     * @param  string $id_type (required)
     * @param  string $captcha (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function v1JpjDrivingTestResultsGetRequest($id_no, $id_type, $captcha = null)
    {
        // verify the required parameter 'id_no' is set
        if ($id_no === null || (is_array($id_no) && count($id_no) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id_no when calling v1JpjDrivingTestResultsGet'
            );
        }
        // verify the required parameter 'id_type' is set
        if ($id_type === null || (is_array($id_type) && count($id_type) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id_type when calling v1JpjDrivingTestResultsGet'
            );
        }

        $resourcePath = '/v1/jpj/driving-test-results';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($id_no !== null) {
            $queryParams['id_no'] = ObjectSerializer::toQueryValue($id_no);
        }
        // query params
        if ($id_type !== null) {
            $queryParams['id_type'] = ObjectSerializer::toQueryValue($id_type);
        }
        // query params
        if ($captcha !== null) {
            $queryParams['captcha'] = ObjectSerializer::toQueryValue($captcha);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation v1JpjMotorVehicleExpiryGet
     *
     * @param  string $id_no id_no (required)
     * @param  string $id_type id_type (required)
     * @param  string $vehicle_no vehicle_no (required)
     * @param  string $captcha captcha (optional)
     *
     * @throws \iimmpact\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \iimmpact\Model\VehicleExpiryResponse
     */
    public function v1JpjMotorVehicleExpiryGet($id_no, $id_type, $vehicle_no, $captcha = null)
    {
        list($response) = $this->v1JpjMotorVehicleExpiryGetWithHttpInfo($id_no, $id_type, $vehicle_no, $captcha);
        return $response;
    }

    /**
     * Operation v1JpjMotorVehicleExpiryGetWithHttpInfo
     *
     * @param  string $id_no (required)
     * @param  string $id_type (required)
     * @param  string $vehicle_no (required)
     * @param  string $captcha (optional)
     *
     * @throws \iimmpact\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \iimmpact\Model\VehicleExpiryResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function v1JpjMotorVehicleExpiryGetWithHttpInfo($id_no, $id_type, $vehicle_no, $captcha = null)
    {
        $returnType = '\iimmpact\Model\VehicleExpiryResponse';
        $request = $this->v1JpjMotorVehicleExpiryGetRequest($id_no, $id_type, $vehicle_no, $captcha);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\iimmpact\Model\VehicleExpiryResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation v1JpjMotorVehicleExpiryGetAsync
     *
     * 
     *
     * @param  string $id_no (required)
     * @param  string $id_type (required)
     * @param  string $vehicle_no (required)
     * @param  string $captcha (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1JpjMotorVehicleExpiryGetAsync($id_no, $id_type, $vehicle_no, $captcha = null)
    {
        return $this->v1JpjMotorVehicleExpiryGetAsyncWithHttpInfo($id_no, $id_type, $vehicle_no, $captcha)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v1JpjMotorVehicleExpiryGetAsyncWithHttpInfo
     *
     * 
     *
     * @param  string $id_no (required)
     * @param  string $id_type (required)
     * @param  string $vehicle_no (required)
     * @param  string $captcha (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1JpjMotorVehicleExpiryGetAsyncWithHttpInfo($id_no, $id_type, $vehicle_no, $captcha = null)
    {
        $returnType = '\iimmpact\Model\VehicleExpiryResponse';
        $request = $this->v1JpjMotorVehicleExpiryGetRequest($id_no, $id_type, $vehicle_no, $captcha);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v1JpjMotorVehicleExpiryGet'
     *
     * @param  string $id_no (required)
     * @param  string $id_type (required)
     * @param  string $vehicle_no (required)
     * @param  string $captcha (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function v1JpjMotorVehicleExpiryGetRequest($id_no, $id_type, $vehicle_no, $captcha = null)
    {
        // verify the required parameter 'id_no' is set
        if ($id_no === null || (is_array($id_no) && count($id_no) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id_no when calling v1JpjMotorVehicleExpiryGet'
            );
        }
        // verify the required parameter 'id_type' is set
        if ($id_type === null || (is_array($id_type) && count($id_type) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id_type when calling v1JpjMotorVehicleExpiryGet'
            );
        }
        // verify the required parameter 'vehicle_no' is set
        if ($vehicle_no === null || (is_array($vehicle_no) && count($vehicle_no) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $vehicle_no when calling v1JpjMotorVehicleExpiryGet'
            );
        }

        $resourcePath = '/v1/jpj/motor-vehicle-expiry';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($id_no !== null) {
            $queryParams['id_no'] = ObjectSerializer::toQueryValue($id_no);
        }
        // query params
        if ($id_type !== null) {
            $queryParams['id_type'] = ObjectSerializer::toQueryValue($id_type);
        }
        // query params
        if ($captcha !== null) {
            $queryParams['captcha'] = ObjectSerializer::toQueryValue($captcha);
        }
        // query params
        if ($vehicle_no !== null) {
            $queryParams['vehicle_no'] = ObjectSerializer::toQueryValue($vehicle_no);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation v1JpjSummonsGet
     *
     * @param  string $id_no id_no (required)
     * @param  string $id_type id_type (required)
     * @param  string $captcha captcha (optional)
     *
     * @throws \iimmpact\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \iimmpact\Model\JPJSummonsResponse
     */
    public function v1JpjSummonsGet($id_no, $id_type, $captcha = null)
    {
        list($response) = $this->v1JpjSummonsGetWithHttpInfo($id_no, $id_type, $captcha);
        return $response;
    }

    /**
     * Operation v1JpjSummonsGetWithHttpInfo
     *
     * @param  string $id_no (required)
     * @param  string $id_type (required)
     * @param  string $captcha (optional)
     *
     * @throws \iimmpact\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \iimmpact\Model\JPJSummonsResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function v1JpjSummonsGetWithHttpInfo($id_no, $id_type, $captcha = null)
    {
        $returnType = '\iimmpact\Model\JPJSummonsResponse';
        $request = $this->v1JpjSummonsGetRequest($id_no, $id_type, $captcha);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\iimmpact\Model\JPJSummonsResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation v1JpjSummonsGetAsync
     *
     * 
     *
     * @param  string $id_no (required)
     * @param  string $id_type (required)
     * @param  string $captcha (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1JpjSummonsGetAsync($id_no, $id_type, $captcha = null)
    {
        return $this->v1JpjSummonsGetAsyncWithHttpInfo($id_no, $id_type, $captcha)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v1JpjSummonsGetAsyncWithHttpInfo
     *
     * 
     *
     * @param  string $id_no (required)
     * @param  string $id_type (required)
     * @param  string $captcha (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1JpjSummonsGetAsyncWithHttpInfo($id_no, $id_type, $captcha = null)
    {
        $returnType = '\iimmpact\Model\JPJSummonsResponse';
        $request = $this->v1JpjSummonsGetRequest($id_no, $id_type, $captcha);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v1JpjSummonsGet'
     *
     * @param  string $id_no (required)
     * @param  string $id_type (required)
     * @param  string $captcha (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function v1JpjSummonsGetRequest($id_no, $id_type, $captcha = null)
    {
        // verify the required parameter 'id_no' is set
        if ($id_no === null || (is_array($id_no) && count($id_no) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id_no when calling v1JpjSummonsGet'
            );
        }
        // verify the required parameter 'id_type' is set
        if ($id_type === null || (is_array($id_type) && count($id_type) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id_type when calling v1JpjSummonsGet'
            );
        }

        $resourcePath = '/v1/jpj/summons';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($id_no !== null) {
            $queryParams['id_no'] = ObjectSerializer::toQueryValue($id_no);
        }
        // query params
        if ($id_type !== null) {
            $queryParams['id_type'] = ObjectSerializer::toQueryValue($id_type);
        }
        // query params
        if ($captcha !== null) {
            $queryParams['captcha'] = ObjectSerializer::toQueryValue($captcha);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
