<?php
/**
 * DrivingTestRespone
 *
 * PHP version 5
 *
 * @category Class
 * @package  iimmpact
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * IIMMPACT API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2020-09-14T13:01:14Z
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.17
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace iimmpact\Model;

use \ArrayAccess;
use \iimmpact\ObjectSerializer;

/**
 * DrivingTestRespone Class Doc Comment
 *
 * @category Class
 * @package  iimmpact
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DrivingTestRespone implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'DrivingTestRespone';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'enquiry_test_part_1' => '\iimmpact\Model\DrivingTestResponeEnquiryTestPart1[]',
        'enquiry_practical_test' => '\iimmpact\Model\DrivingTestResponeEnquiryTestPart1[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'enquiry_test_part_1' => null,
        'enquiry_practical_test' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'enquiry_test_part_1' => 'Enquiry Test Part 1',
        'enquiry_practical_test' => 'Enquiry Practical Test'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'enquiry_test_part_1' => 'setEnquiryTestPart1',
        'enquiry_practical_test' => 'setEnquiryPracticalTest'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'enquiry_test_part_1' => 'getEnquiryTestPart1',
        'enquiry_practical_test' => 'getEnquiryPracticalTest'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['enquiry_test_part_1'] = isset($data['enquiry_test_part_1']) ? $data['enquiry_test_part_1'] : null;
        $this->container['enquiry_practical_test'] = isset($data['enquiry_practical_test']) ? $data['enquiry_practical_test'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets enquiry_test_part_1
     *
     * @return \iimmpact\Model\DrivingTestResponeEnquiryTestPart1[]
     */
    public function getEnquiryTestPart1()
    {
        return $this->container['enquiry_test_part_1'];
    }

    /**
     * Sets enquiry_test_part_1
     *
     * @param \iimmpact\Model\DrivingTestResponeEnquiryTestPart1[] $enquiry_test_part_1 enquiry_test_part_1
     *
     * @return $this
     */
    public function setEnquiryTestPart1($enquiry_test_part_1)
    {
        $this->container['enquiry_test_part_1'] = $enquiry_test_part_1;

        return $this;
    }

    /**
     * Gets enquiry_practical_test
     *
     * @return \iimmpact\Model\DrivingTestResponeEnquiryTestPart1[]
     */
    public function getEnquiryPracticalTest()
    {
        return $this->container['enquiry_practical_test'];
    }

    /**
     * Sets enquiry_practical_test
     *
     * @param \iimmpact\Model\DrivingTestResponeEnquiryTestPart1[] $enquiry_practical_test enquiry_practical_test
     *
     * @return $this
     */
    public function setEnquiryPracticalTest($enquiry_practical_test)
    {
        $this->container['enquiry_practical_test'] = $enquiry_practical_test;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


