<?php
/**
 * CarInsuranceResponeTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  iimmpact
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * IIMMPACT API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2020-09-14T13:01:14Z
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.17
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace iimmpact;

/**
 * CarInsuranceResponeTest Class Doc Comment
 *
 * @category    Class
 * @description CarInsuranceRespone
 * @package     iimmpact
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CarInsuranceResponeTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CarInsuranceRespone"
     */
    public function testCarInsuranceRespone()
    {
    }

    /**
     * Test attribute "message"
     */
    public function testPropertyMessage()
    {
    }

    /**
     * Test attribute "make"
     */
    public function testPropertyMake()
    {
    }

    /**
     * Test attribute "model"
     */
    public function testPropertyModel()
    {
    }

    /**
     * Test attribute "year_make"
     */
    public function testPropertyYearMake()
    {
    }

    /**
     * Test attribute "chassis_no"
     */
    public function testPropertyChassisNo()
    {
    }

    /**
     * Test attribute "engine_no"
     */
    public function testPropertyEngineNo()
    {
    }

    /**
     * Test attribute "seating_capacity"
     */
    public function testPropertySeatingCapacity()
    {
    }

    /**
     * Test attribute "variant"
     */
    public function testPropertyVariant()
    {
    }

    /**
     * Test attribute "veh_image"
     */
    public function testPropertyVehImage()
    {
    }

    /**
     * Test attribute "next_ncd_per_centage"
     */
    public function testPropertyNextNcdPerCentage()
    {
    }

    /**
     * Test attribute "next_ncd_exp_date"
     */
    public function testPropertyNextNcdExpDate()
    {
    }

    /**
     * Test attribute "current_policy"
     */
    public function testPropertyCurrentPolicy()
    {
    }
}
