<?php
/**
 * DrivingTestResponeEnquiryTestPart1Test
 *
 * PHP version 5
 *
 * @category Class
 * @package  iimmpact
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * IIMMPACT API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2020-09-14T13:01:14Z
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.17
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace iimmpact;

/**
 * DrivingTestResponeEnquiryTestPart1Test Class Doc Comment
 *
 * @category    Class
 * @description DrivingTestResponeEnquiryTestPart1
 * @package     iimmpact
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DrivingTestResponeEnquiryTestPart1Test extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "DrivingTestResponeEnquiryTestPart1"
     */
    public function testDrivingTestResponeEnquiryTestPart1()
    {
    }

    /**
     * Test attribute "date_of_test"
     */
    public function testPropertyDateOfTest()
    {
    }

    /**
     * Test attribute "test_type"
     */
    public function testPropertyTestType()
    {
    }

    /**
     * Test attribute "license_class"
     */
    public function testPropertyLicenseClass()
    {
    }

    /**
     * Test attribute "test_venue"
     */
    public function testPropertyTestVenue()
    {
    }

    /**
     * Test attribute "result"
     */
    public function testPropertyResult()
    {
    }
}
