<?php
/**
 * JPJSummonsResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  iimmpact
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * IIMMPACT API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2020-09-14T13:01:14Z
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.17
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace iimmpact;

/**
 * JPJSummonsResponseTest Class Doc Comment
 *
 * @category    Class
 * @description JPJSummonsResponse
 * @package     iimmpact
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class JPJSummonsResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "JPJSummonsResponse"
     */
    public function testJPJSummonsResponse()
    {
    }

    /**
     * Test attribute "summon_notice_no_"
     */
    public function testPropertySummonNoticeNo_()
    {
    }

    /**
     * Test attribute "notice_type"
     */
    public function testPropertyNoticeType()
    {
    }

    /**
     * Test attribute "vehicle_registration_no_"
     */
    public function testPropertyVehicleRegistrationNo_()
    {
    }

    /**
     * Test attribute "date__time_of_offenses"
     */
    public function testPropertyDateTimeOfOffenses()
    {
    }

    /**
     * Test attribute "notice_compound_payment_date"
     */
    public function testPropertyNoticeCompoundPaymentDate()
    {
    }

    /**
     * Test attribute "offenses_type"
     */
    public function testPropertyOffensesType()
    {
    }

    /**
     * Test attribute "offenses_location"
     */
    public function testPropertyOffensesLocation()
    {
    }
}
